<?php
ini_set('max_execution_time', 0);
include("connect.php");
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
error_reporting(E_ALL);


$file = fopen('product.csv', 'r');
while (($line = fgetcsv($file)) !== FALSE) {
   //$line[0] = '1004000018' in first iteration
   $rows=array(
       'price'=>$line[3]
   );
   $where	= "name='" . $line[1] . "' AND isDelete=0";
   $db->rpupdate('product', $rows, $where);
}
fclose($file);