<?php
ini_set('max_execution_time', 0);
include("connect.php");
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
error_reporting(E_ALL);
include('../include/resize_image.php');
$image = new SimpleImage();

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://tufan.ezsellsolutions.com/customer/api/auth');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"username\":\"zillifurniture@gmail.com\",\"password\":\"Zilli7265$\"}");

$headers = array();
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = json_decode(curl_exec($ch));
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
$IMAGEPATH_T                 = PRODUCT_T;
$IMAGEPATH_A                 = PRODUCT_A;
$IMAGEPATH                     = PRODUCT;
$IMAGEPATH_THUMB_A             = PRODUCT_THUMB_A;
$IMAGEPATH_LIST_THUMB_A     = PRODUCT_LIST_THUMB_A;

$IMAGEPATH_ALT_T         = PRODUCT_ALT_T;
$IMAGEPATH_ALT_A         = PRODUCT_ALT_A;
$IMAGEPATH_ALT             = PRODUCT_ALT;
$IMAGEPATH_ALT_THUMB_A  = PRODUCT_ALT_THUMB_A;
$IMAGEPATH_ALT_LIST_THUMB_A = PRODUCT_ALT_LIST_THUMB_A;

$IMAGEPATH_BANNER_A = CATE_BANNER_A;


$token = $result->token;

echo $token;exit;
$collection_array=array();
for ($page = 1; $page <= 29; $page++) {
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://tufan.ezsellsolutions.com/customer/api/product?page=' . $page . '&offset=100');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    $headers = array();
    $headers[] = 'Authorization: Bearer ' . $token;
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $products = json_decode(curl_exec($ch));
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    if ($page != 14 && $page != 15 && $page != 17 && $page != 18 && $page != 19 && $page != 20 && count($products) > 0) {

        echo "Product Page: " . $page . '<br>';
        $where         = " name='Rugs' AND isDelete=0";
        $ctable_r     = $db->rpgetData('category', "id", $where);
        $ctable_d     = @mysqli_fetch_array($ctable_r);
        $category_id = $ctable_d['id'];

        $where         = " name='Contemporary Rugs' AND isDelete=0";
        $ctable_r     = $db->rpgetData('sub_category', "id", $where);
        $ctable_d     = @mysqli_fetch_array($ctable_r);
        $sub_category_id = $ctable_d['id'];

        foreach ($products as $product) {
            $product = (array)$product;
            echo "Product Collection: " . $product['Collection'] . '<br>';
            $group_id = '';

            if (strcasecmp($product['Collection'], 'Renata') == 0) {
                $where         = " name='Group 909' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 909',
                        'group-909'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Renata' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Renata',
                        'renata',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Rusena') == 0) {
                $where         = " name='Group 910' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 910',
                        'group-910'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Rusena' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Rusena',
                        'rusena',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Lola') == 0) {
                $where         = " name='Group 911' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 911',
                        'group-911'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Lola' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Lola',
                        'lola',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'comfort') == 0) {
                $where         = " name='Group 912' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 912',
                        'group-912'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Comfort' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Comfort',
                        'comfort',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Aspen') == 0) {
                $where         = " name='Group 913' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 913',
                        'group-913'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Aspen' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Aspen',
                        'aspen',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Andrea') == 0) {
                $where         = " name='Group 914' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 914',
                        'group-914'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Andrea' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Andrea',
                        'andrea',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Emilia') == 0) {
                $where         = " name='Group 915' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 915',
                        'group-915'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Emilia' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Emilia',
                        'emilia',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Barcelona') == 0) {
                $where         = " name='Group 916' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 916',
                        'group-916'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Barcelona' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Barcelona',
                        'barcelona',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Bloom') == 0) {
                $where         = " name='Group 917' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 917',
                        'group-917'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Bloom' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Bloom',
                        'bloom',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Murana') == 0) {
                $where         = " name='Group 918' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 918',
                        'group-918'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Murana' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Murana',
                        'murana',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Karmina') == 0) {
                $where         = " name='Group 919' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 919',
                        'group-919'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Karmina' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Karmina',
                        'karmina',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Nadia') == 0) {
                $where         = " name='Group 920' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 920',
                        'group-920'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Nadia' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Nadia',
                        'nadia',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Niza') == 0) {
                $where         = " name='Group 921' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 921',
                        'group-921'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Niza' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Niza',
                        'niza',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Astral') == 0) {
                $where         = " name='Group 922' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 922',
                        'group-922'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Astral' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Astral',
                        'astral',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Logan') == 0) {
                $where         = " name='Group 923' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 923',
                        'group-923'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Logan' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Logan',
                        'logan',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Azura') == 0) {
                $where         = " name='Group 924' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 924',
                        'group-924'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Azura' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Azura',
                        'azura',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Davis') == 0) {
                $where         = " name='Group 925' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 925',
                        'group-925'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Davis' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Davis',
                        'davis',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            } else if (strcasecmp($product['Collection'], 'Veranda') == 0) {
                $where         = " name='Group 926' AND isDelete=0";
                $ctable_r     = $db->rpgetData('product_group', "id", $where);
                $group     = @mysqli_fetch_array($ctable_r);
                if ($group == '') {
                    $rows = array(
                        'name',
                        'slug'
                    );
                    $values = array(
                        'Group 926',
                        'group-926'
                    );
                    $group_id =  $db->rpinsert('product_group', $values, $rows);
                }else{
                    $group_id=$group['id'];
                }
                $where         = " name='Veranda' AND isDelete=0";
                $ctable_r     = $db->rpgetData('sub_sub_category', "id", $where);
                $sub_category     = @mysqli_fetch_array($ctable_r);
                if ($sub_category == '') {

                    $banner_image_path = time() . "-subsubcate-" . rand() . '.jpg';
                    $imgdata = file_get_contents($product['images'][0]);
                    file_put_contents($IMAGEPATH_A . $banner_image_path, $imgdata);
                    @move_uploaded_file($_FILES["banner_image_path"]["tmp_name"], $IMAGEPATH_BANNER_A . $banner_image_path);

                    ////// - Product Thumb Starts - //////
                    $image->load($IMAGEPATH_BANNER_A . $banner_image_path);
                    $image->resize(1349, 360);
                    $image->save($IMAGEPATH_BANNER_A . $banner_image_path);
                    $rows = array(
                        'name',
                        'slug',
                        'cate_id',
                        'sub_cate_id',
                        'banner_image'
                    );
                    $values = array(
                        'Veranda',
                        'veranda',
                        $category_id,
                        $sub_category_id,
                        $banner_image_path
                    );
                    $sub_sub_category_id =  $db->rpinsert('sub_sub_category', $values, $rows);
                }
                else{
                    $sub_sub_category_id=$sub_category['id'];
                }
            }

            if ($group_id != '') {
                echo "Product Add " . $product['sku'] . '</br>';

                $image_path = time() . "-pro-" . rand() . '.jpg';
                $imgdata = file_get_contents($product['images'][0]);
                file_put_contents($IMAGEPATH_A . $image_path, $imgdata);
                $image->createThumbnail($image_path, 154, 106, $IMAGEPATH_A . $image_path, $IMAGEPATH_THUMB_A . $image_path);
                $image->createThumbnail($image_path, 270, 200, $IMAGEPATH_A . $image_path, $IMAGEPATH_LIST_THUMB_A . $image_path);
                $slug = $db->rpcreateSlug($product['sku']);
                $dup_where = "slug = '" . $slug . "' AND cate_id='" . $category_id . "' AND sub_cate_id='" . $sub_category_id . "' AND isDelete=0";
                $r = $db->rpdupCheck('product', $dup_where);
                if ($r) {
                } else {
                    
                    $desc = "";
                    if($product['Color']!=''){
                        $desc.="<b>Color:</b>".$product['Color'].'\n';
                    }
                    if($product['Design']!=''){
                        $desc.="<b>Design:</b>".$product['Design'].'\n';
                    }
                    if($product['Weave']!=''){
                        $desc.="<b>Weave:</b>".$product['Weave'].'\n';
                    }
                    if($product['Material']!=''){
                        $desc.="<b>Material:</b>".$product['Material'].'\n';
                    }
                    if($product['Origin']!=''){
                        $desc.="<b>Origin:</b>".$product['Origin'].'\n';
                    }
                    if($product['Style']!=''){
                        $desc.="<b>Style:</b>".$product['Style'].'\n';
                    }
                    $dimention="".$product['Shipping Dimensions'];
                    $variation                = $db->clean($product['Actual Size']);
                    $variation_slug            = $db->rpcreateSlug($product['Actual Size']);
                    $display_order    = $db->rpgetDisplayOrder('product');
                    if(in_array($product['Sub Category'],$collection_array))
                    {
                        $display_category=0;
                    }
                    else{
                        $display_category=1;
                        array_push($collection_array,$product['Sub Category']);
                    }
                    $rows     = array(
                        "cate_id",
                        "sub_cate_id",
                        "sub_sub_cate_id",
                        "pro_group_id",
                        "color_id",
                        "material_id",
                        "pro_feature_brand",
                        "name",
                        "variation",
                        "variation_slug",
                        "price",
                        "sell_price",
                        "pro_sku",
                        "slug",
                        "isImage",
                        "image",
                        "decs",
                        "feature_dimension",
                        "additional_info",
                        "status",
                        "isProduct",
                        "isDisplayHomePage",
                        "isDisplayCategoryPage",
                        "isEnquiry_product",
                        "display_order",
                        "meta_title",
                        "meta_description",
                        "meta_keywords",
                        "pro_sub_cat"
                    );
                    $values = array(
                        $category_id,
                        $sub_category_id,
                        $sub_sub_category_id,
                        $group_id,
                        0,
                        0,
                        0,
                        $product['sku'],
                        $variation,
                        $variation_slug,
                        0,
                        0,
                        '',
                        $slug,
                        0,
                        $image_path,
                        $desc,
                        $dimention,
                        '',
                        1,
                        0,
                        0,
                        $display_category,
                        0,
                        $display_order,
                        '',
                        '',
                        '',
                        $product['Sub Category']
                    );
                    $last_id = $db->rpinsert('product', $values, $rows, 0);
                    $i = 0;
                    foreach ($product['images'] as $img) {
                        if ($i > 0) {
                            $image_path = time() . "-pro-" . rand() . '.jpg';
                            $imgdata = file_get_contents($img);
                            file_put_contents($IMAGEPATH_ALT_A . $image_path, $imgdata);
                            $image->createThumbnail($image_path, 154, 106, $IMAGEPATH_ALT_A . $image_path, $IMAGEPATH_ALT_THUMB_A . $image_path);
                            $image->createThumbnail($image_path, 270, 200, $IMAGEPATH_ALT_A . $image_path, $IMAGEPATH_ALT_LIST_THUMB_A . $image_path);
                            $display_order    = $db->rpgetDisplayOrder('alt_image', "pid=" . $last_id);
                            $rows     = array(
                                "pid",
                                "isImage",
                                "image_path",
                                "display_order",
                            );
                            $values = array(
                                $last_id,
                                0,
                                $image_path,
                                $display_order,
                            );
                            $db->rpinsert('alt_image', $values, $rows);
                        }
                        $i++;
                    }
                }
            }
        }
    }
}
